**Numpy Arrays**

In [ ]:
lst=[1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(lst)

array([1, 2, 3])

In [4]:
arr=np.array(lst)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods

**Arange**

Numpy Range function is similar to python range function. It takes start point, stop point and step size. Returns including starting point but not stopping point

In [8]:
np.arange(0,10)    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)   #Returns even numbers between 0 and 10

array([ 0,  2,  4,  6,  8, 10])

**Zeros and Ones Matrices**

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((3,5))     # Double pharantesis!!!

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

**Linspace**

In [18]:
np.linspace(0,5,10)  # takes start, stop and number of int. returns number of int. 
                     # between 0 and 5 

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

**Identity matrix**

In [19]:
np.eye(4)            

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

**Random Number Generators**

In [20]:
np.random.rand(4)    #uniform dagilimda random sayi uretir

array([ 0.26523744,  0.2346268 ,  0.86690468,  0.15668029])

In [21]:
np.random.rand(3,5)   #3*5 uniform random sayi matrixi dondurur

array([[ 0.81585925,  0.19961991,  0.20829669,  0.97017822,  0.24558941],
       [ 0.1731335 ,  0.0493609 ,  0.31040799,  0.7554974 ,  0.59702336],
       [ 0.79925495,  0.97644135,  0.12610869,  0.52702616,  0.12450949]])

In [23]:
np.random.randn(4)    # #normal dagilimda random sayi uretir

array([ 1.63175852, -1.30091089,  1.4475842 , -0.15026852])

In [24]:
np.random.randn(3,5)

array([[ 0.51274667, -0.32900368, -0.88253386,  0.68226682, -0.74997209],
       [-0.93360607,  0.37643569, -0.87772317,  0.64232793,  0.58744631],
       [ 0.78096996, -1.60476625, -0.4310894 , -1.20031473,  1.93631746]])

In [3]:
np.random.randint(2,8,3)   #RETURNS 3 integers, between 2 (inclusive) and 8 (exclusive)

NameError: name 'np' is not defined

**Array Methods**

In [61]:
arr=np.arange(20)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
arr.reshape(4,5)    #reshape fonksiyonu icin arr'in size ile reshape'in size ayni olmali

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
ranarr=np.random.randint(0,50,10)

In [71]:
ranarr

array([18,  2,  7, 16, 34,  3,  7, 40, 30, 40])

In [72]:
ranarr.max()

40

In [74]:
ranarr.argmax()     # Indicate that index location of max value of this array

7

In [75]:
ranarr.argmin()    # Indicate that index location of min value of this array

1

In [78]:
arr.shape          # returns the size of arr, here we have 1 dimentional vector

(20L,)

In [79]:
arrr=arr.reshape(4,5)

In [80]:
arrr.shape        # returns 4*5

(4L, 5L)

In [83]:
arr.dtype         # returns data type of the array

dtype('int32')