# NumPy Indexing and Selection

In [ ]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Selection**

In [4]:
arr[5]

5

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[-1]

10

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[:5]=100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
slice_of_array= arr[:5]

In [14]:
slice_of_array[:]=99    # sadece slice_of_array degil original arrayde degisiyor

In [15]:
slice_of_array

array([99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy=arr.copy()    # Asil arrayi kopyalarsak original olan arrayi degistirmemeis oluruz

In [19]:
arr_copy[:]=28

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28])

** Indexing Matrices**

In [23]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[1][1]    #1. [] row number, 2. [] colomn number

25

In [29]:
arr_2d[0]   # returns first row in the matrix

array([ 5, 10, 15])

In [31]:
arr_2d[1,2]   # 1. numara row number, 2. numara colonm number

30

In [33]:
arr_2d[1:,1:]    # matrix'in belirli bi bolumunu alir

array([[25, 30],
       [40, 45]])

**Selection**

In [34]:
arr=np.arange(1,11)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
bool_arr=arr>5

In [39]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [40]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr_2d=np.arange(50).reshape(5,10)

In [43]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])